 export const image = [
    {
      id:1,
      img:"./image/gym1.jpg",
      title:"title1",
      desc:"desc1",
    },
    {
      id:2,
      img:"./image/gym3.jpg",
      title:"title2",
      desc:"desc2",
    },
    {
      id:3,
      img:"./image/gym4.jpg",
      title:"title3",
      desc:"desc3",
    },
    {
      id:4,
      img:"./image/gym5.jpg",
      title:"title4",
      desc:"desc4",
    },
    {
      id:5,
      img:"./image/gym5.jpg",
      title:"title5",
      desc:"desc5",
    },
    {
      id:6,
      img:"./image/gym5.jpg",
      title:"title6",
      desc:"desc6",
    },
    {
      id:7,
      img:"./image/gym5.jpg",
      title:"title7",
      desc:"desc7",
    },
    {
      id:8,
      img:"./image/gym5.jpg",
      title:"title8",
      desc:"desc8",
    },
    {
        id:9,
        img:"./image/gym5.jpg",
        title:"title9",
      desc:"desc9",
      },
      {
        id:10,
        img:"./image/gym5.jpg",
        title:"title10",
      desc:"desc10",
      },
      {
        id:11,
        img:"./image/gym4.jpg",
        title:"title11",
      desc:"desc11",
      },
      {
        id:12,
        img:"./image/gym3.jpg",
        title:"title12",
      desc:"desc12",
      },
      {
        id:13,
        img:"./image/gym1.jpg",
        title:"title13",
      desc:"desc13",
      },
  ];
  export const imagebig = [
    {
      id:1,
      img:"./image/gym1.jpg",
    },
    {
      id:2,
      img:"./image/gym3.jpg",
    },
    {
      id:3,
      img:"./image/gym4.jpg",
    },
    {
      id:4,
      img:"./image/gym5.jpg",
    },
    
  ];
  export const photo = [
    {
      id:1,
      img:"https://images.pexels.com/photos/758733/pexels-photo-758733.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
    {
      id:2,
      img:"https://images.pexels.com/photos/21261/pexels-photo.jpg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
    {
      id:3,
      img:"https://images.pexels.com/photos/567973/pexels-photo-567973.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
    {
      id:4,
      img:"https://images.pexels.com/photos/776653/pexels-photo-776653.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
     {
      id:5,
      img:"https://images.pexels.com/photos/54630/japanese-cherry-trees-flowers-spring-japanese-flowering-cherry-54630.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
     {
      id:6,
      img:"https://images.pexels.com/photos/131046/pexels-photo-131046.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
     {
      id:7,
      img:"https://images.pexels.com/photos/302515/pexels-photo-302515.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
     {
      id:8,
      img:"https://images.pexels.com/photos/301682/pexels-photo-301682.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
     {
      id:9,
      img:"https://images.pexels.com/photos/933054/pexels-photo-933054.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
    },
  
   
    
  ];